# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raum für ihr Recht
description: ""
baseurl: ""
url: "http://joomladaytemplate.niels-nuebel.de"
googleanalyticss:  UA-XXXXX-1

# Build settings
markdown: kramdown

#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, Gemfile, Gemfile.lock, CNAME]
sass:
  sass_dir: _sass
  style: compressed

repository: nielsnuebel/joomladaytemplate

# Site nav
nav:

- name: Home
  link: "/#home"
  class: "scrollto"

- name: VITA
  link: "/#vita"
  class: "scrollto"

- name: Kanzleischwerpunkt
  link: "/#schwerpunkte"
  class: "scrollto"

- name: Leistungskatalog
  link: "/#leistungen"
  class: "scrollto"

- name: Veröffentlichungen
  link: "/#veroeffentlichungen"
  class: "scrollto"

- name: Kontakt
  link: "/#kontakt"
  class: "scrollto"